version: "3.7"
services:
  sample-api-service:
    container_name: sample-api-service-container
    build:
      context: sample-api-service/.
      args:
        - MAVEN_OPTS=-DskipTests -DskipITs=true -Dskip.ut=true
        - TAG=0.1
    ports:
      - "8080:8080"

  api-mock:
    container_name: api-mock
    image: wiremock/wiremock:3.3.1
    command: "--verbose"
    volumes:
      - ./mock/data:/home/wiremock
    ports:
      - "8081:8080"
    depends_on:
      - sample-api-service
    healthcheck:
      test: curl -f localhost:8080/__admin/mappings
      interval: 5s
      retries: 60
      start_period: 30s
      timeout: 30s